<?xml version="1.0" encoding="utf-8"?><Database Name="Zain" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=&quot;\\psf\home\documents\visual studio 2013\Projects\ZainGym\ZainGym\Data\Zain.mdf&quot;;Integrated Security=True" SettingsObjectName="Demo.Properties.Settings" SettingsPropertyName="ZainConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Memberships" Member="Memberships">
    <Type Name="Membership">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[From]" Member="From" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[To]" Member="To" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Person_Membership" Member="Person" ThisKey="PersonId" OtherKey="Id" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="Person_Membership" Member="Memberships" ThisKey="Id" OtherKey="PersonId" Type="Membership" />
    </Type>
  </Table>
</Database>